[FEAT] Add example about "select several BPMN Html Elements for interaction"
process-analytics/bpmn-visualization-examples pull request #124
Opened 2020-12-30 14:33 UTC by tbouffard

**WIP**

closes #123 

**Live environment of examples**

https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/123-add_example_with_select_bpmn_elements_by_kind/examples/index.html

2020-12-30 16:51 UTC, tbouffard commented
Here are some screencasts done during developments. The final implementation is closed to what they show.

![select_end_event_v1_01_name_or_id](https://user-images.githubusercontent.com/27200110/103368348-96918a80-4ac7-11eb-85f6-21333fdc3861.gif)

![select_end_event_v1_02_also_in_subprocesses](https://user-images.githubusercontent.com/27200110/103368350-972a2100-4ac7-11eb-8de2-6eb35a4b247f.gif)

![select_pools_collapse_others_v1](https://user-images.githubusercontent.com/27200110/103368351-97c2b780-4ac7-11eb-9305-efbc247af144.gif)

![select_pools_hide_others_v1](https://user-images.githubusercontent.com/27200110/103368353-985b4e00-4ac7-11eb-9e33-c419e2990c3d.gif)

2021-01-11 09:48 UTC, csouchet commented on examples/custom-interaction/select-elements-by-bpmn-kind/README.md
> +If you want to process the BPMN Kinds differently, you can filter the array as in the following if you first
It's not important, but everywhere is a 'k' and not 'K':

```suggestion
If you want to process the BPMN kinds differently, you can filter the array as in the following if you first
```

2021-01-11 09:54 UTC, csouchet commented on examples/custom-interaction/select-elements-by-bpmn-kind/README.md
> +It also allows hiding or collapsing `Pools`. The `bpmn-visualization` API is used to retrieve to the `Pool` ids but the `Pool`
```suggestion
It also allows hiding or collapsing `Pools`. The `bpmn-visualization` API is used to retrieve to the `Pool` ids, but the `Pool`
```

2021-01-11 09:56 UTC, csouchet commented on examples/custom-interaction/select-elements-by-bpmn-kind/README.md
> +display if then fully managed by custom mxGraph code. \
Do you mean ?

```suggestion
display is then fully managed by custom mxGraph code. \
```

2021-01-11 10:06 UTC, csouchet commented
## On MacOs

### Firefox
![image](https://user-images.githubusercontent.com/4921914/104167497-ae88d880-53fc-11eb-9f2a-02c55cf818b2.png)
### Chrome
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/4921914/104167555-d0825b00-53fc-11eb-872b-c4a1f41d00f9.png">
### Safari
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/4921914/104167645-fe679f80-53fc-11eb-802d-be2ef9100ef1.png">

2021-01-11 10:08 UTC, csouchet requested changes
There is a problem of rendering/display:
- No data in the _Select_
- The BPMN Container is too far to the left

2021-01-11 10:43 UTC, tbouffard commented
> There is a problem of rendering/display:
> 
>     * No data in the _Select_
> 
>     * The BPMN Container is too far to the left

**No data in the Select**: the issue only occurs when accessing the example with the CDN url. It returns a wrong MIME type for the lib js file
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/123-add_example_with_select_bpmn_elements_by_kind/examples/__tmp/bpmn-visualization@5be173e4.js: MIME type `text/html`
Actually, we get a 404 error when requesting this resource and in that case, statically.io serves a 404 html page, so this is why we got the html MIME type.
I have reproduced the issue on Ubuntu 18.04 with Chrome and Firefox

This js file has been added to the branch after the CDN cache has been filled and the cache is then not updated. See https://statically.io/docs/using-staticzap/
> All files will be cached on the CDN for 1 year, except for these listed branch that are cached for only 1 day:
>
>     main
>     master
>     dev
>     develop
>     gh-pages



**The BPMN Container is too far to the left**: consequence of the Javascript loading issue

2021-01-11 10:44 UTC, csouchet approved these changes

2021-01-11 10:48 UTC, merged