feat(prediction): add popup popover
process-analytics/bpmn-visualization-examples pull request #528
Opened 2023-07-21 12:57 UTC by csouchet

**Live environment of examples**

[https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/260-add_popup_popover/examples/index.html](https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/260-add_popup_popover/examples/index.html)

https://github.com/process-analytics/bpmn-visualization-examples/assets/4921914/1cd6bae1-2fb6-4181-9751-566082c64c08

Closes #530

2023-07-21 17:07 UTC, tbouffard requested changes
✔️ rendering: very nice, great job ❤️ https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/da46821/demo/prediction/index.html
❌ IMHO we should change the way the tippy/popper assets are loaded (see my comments)
❌ the predicted dates are not releavant for the domain. It is about baking and delivering pizza, so the duration should be minutes (or eventually few hours for late). I cannot be on time and take 2 days 😄 

![image](https://github.com/process-analytics/bpmn-visualization-examples/assets/27200110/0870c836-3e4a-4c01-a715-9a115641232f)

2023-07-21 17:07 UTC, tbouffard commented on demo/prediction/js/prediction-use-case.js
> +        this._style = new PredicatedLateStyle(this._bpmnVisualization.bpmnElementsRegistry, `${this.type}-bpmn-container`);
**question:** can't we retrieve the id from the UseCase class? we are leaking the internal implementation of UseCase here!

2023-07-24 07:27 UTC, csouchet commented on demo/prediction/index.html
> +    <script src="https://unpkg.com/tippy.js@6"></script>
I just follow the documentation of tippy: https://atomiks.github.io/tippyjs/v6/getting-started/#2-cdn

2023-07-24 07:32 UTC, csouchet commented on demo/prediction/js/data.js
> +     */
Thanks for the tips :wink:

2023-07-24 10:02 UTC, merged